### ISSUE TITLE
BGP4r has active deadlock

### ISSUE THREAD

**Issue by cmouse** [jesnault/bgp4r#3]
I have been trying to debug for few days why bgp4r spends so much CPU, and it appears it has two threads in active deadlock (most likely). I have not been able to figure out where it exactly is, but 

16702 ?        -    4119:13 /usr/bin/ruby /opt/bgp-peer/bgp-peer.rb run
    - -        Ssl    0:02 -
    - -        Ssl  2055:20 -
    - -        Ssl    0:33 -
    - -        Ssl    0:12 -
    - -        Ssl    0:04 -
    - -        Rsl  2057:05 -
    - -        Ssl    0:34 -
    - -        Ssl    0:12 -
    - -        Ssl    0:04 -
    - -        Ssl    2:57 -
    - -        Ssl    0:24 -
    - -        Ssl    0:23 -
    - -        Ssl    0:00 -
    - -        Ssl    0:00 -
    - -        Ssl    0:00 -

This shows that two threads are currently competing for some lock. If I try debug this, with, say ruby function tracing, it goes away because the function tracing causes delays. Any ideas or should I try get some more debugging?

**Comment by jesnault** [comment]
more debugging and info would help
ruby interpreter should detect thread locking: thread deadlock  or cpu hog?

**Comment by cmouse** [comment]
It seems to use one cpu completely. A cpu hog. Both threads awake in turn to try lock something.  Could not find any obvious locking, though.

**Comment by jesnault** [comment]
have you tried with different ruby versions?
what's your setup?
is this something that used to work?
is this happening systematically?
what are you doing with bgp4r, can you share your code?

**Comment by cmouse** [comment]
It happens every time. I've tried ruby 1.9 and 2.0. https://github.com/cmouse/bgp-advertize-when-alive is the code. It only happens on multicore systems.

**Comment by jesnault** [comment]
You need to determine where the CPU is hog is. 
I would not start with suspecting bgp4r as bgp-advertize-when-alive adds few threads + loops + deamon code, i.e the cpu hog is not necessarily in bgp4r code.

**Comment by cmouse** [comment]
Possible of course. Although I have spent few days debugging this and it does seem to be case of active deadlock. I'll see if I can produce more debug info. Ruby isn't exactly easiest to debug in these cases.

**Comment by cmouse** [comment]
I now created a simplified version, https://gist.github.com/cmouse/27c2af929d0e3c31d24b, which has no Daemons or threads on it's own, and I still get this problem.

**Comment by cmouse** [comment]
@jesnault have you had time to look at the latest somewhat stripped example?

**Comment by jesnault** [comment]
Sorry got distracted ( busy ) haven't had time to play with it.
