### ISSUE TITLE
Origin Validation community

### ISSUE THREAD

**Issue by ytti** [jesnault/bgp4r#8]
https://tools.ietf.org/html/rfc8097

I tried to implement this but looks like I'm not really understanding what is going on.

It is type 0x43, subtype 0x00, but the case statement only looks at subtypes. I tried ghetto solution, just to understand it better and created condition to punt type == 0x43 && subtype = 0x00 to new Origin_validation class, but I couldn't figure out what the infrastructure wants and ended up getting raised by string/array problems with pack.

It should really be just  0x4300 and then 0,1,3 as last byte. 

Many thanks for your work for bgp4r, it is old, but it's still really convenient and there aren not actually many proper library BGP implementations for any language. There are bunch of daemons which are not useable as libraries and have no or bad APIS fit for very few use-cases.

**Comment by jesnault** [comment]
Glad to hear that this library is still useful :) 
Will try and come up with something today.

**Comment by jeanmichel-gh** [comment]
I believe the issue has been resolved.
